### PR TITLE
[ECO-609]: Enable/Disable button while connecting/disconnecting

### PR DESCRIPTION
**Pull request by robjperez**

### CODE REVIEW

**Comment by hbaqai** [comment]
After making sure Android studio is up to date I'm getting a compile error when I build your branch. In the app module's `build.gradle` file, line 33 has the error:

```
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.0.0-alpha1, 25.3.1. Examples include com.android.support:support-core-utils:26.0.0-alpha1 and com.android.support:design:25.3.1 

There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion.)
```

When I build the project I see a related error:

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:recyclerview-v7:26.0.0-alpha1] AndroidManifest.xml:24:9-38 value=(26.0.0-alpha1).
```

It looks like the project is using `+` notation in the library versions specified, and that is causing some incompatibilities. I know this isn't part of your PR directly, but because it's causing a compile error, I believe it should be addressed.

**Comment by robjperez** [comment]
You are right, the project does not compile out of the box, but I think this is a problem, not of this repo but the annotations-textchat module which is uploaded to maven. More precisely, this is the problem:

https://github.com/opentok/accelerator-textchat-android/blob/master/textchat-acc-pack/build.gradle#L112

We must use specific versions for our library packages, or this will happen...

We can fix it now in this repo by using 26 (that's what I'm using locally to test it), but I think the problem has to be fixed in the annotations-textchat repo instead. (Given that 26 is alpha yet...)

In any case, this is out of the scope of this PR, I think.

**Comment by robjperez** [comment]
Created this ticket to fix the problem in the origin:

https://tokbox.atlassian.net/browse/ECO-641

**Comment by hbaqai** [comment]
@robjperez , we're doing that in this project too, though.

Can we update the build.gradle in this repo to follow the same advice? Even if it isn't what is causing the compile errors in this PR, the root of the problem is the violation of the same principle.

**Comment by robjperez** [comment]
Although using a `+` is always not recommended, it is not that bad for non-library projects like this one.

Once this PR: https://github.com/opentok/accelerator-textchat-android/pull/37 is merged and uploaded to maven the build problems should be fixed here

**Comment by marinaserranomontes** [comment]
👍

**Comment by marinaserranomontes** [comment]
@robjperez @hbaqai accelerator-textchat 1.0.3 is out

**Pull request merged**
